### ISSUE TITLE
Check failed error

### ISSUE THREAD

**Issue by iqbalnaved** [zeakey/LDLForest#1]
Hi

While running the run.py I received the following error:

Check failed: bottom[1]->shape()[1] == neural_decision_forest_param.num_classes() (5 vs. 2) num_classes_ must be equal to bottom[1]->shape[1]

I am using the Movie.mat from the Dataset as set in the code, and for both test-kld.prototxt and train.prototoxt , output_num: 512,  what am I doing wrong?

Thanks.
  
  EDIT: I commented out the assertion check in neural_decision_forest_layer.cpp , and it worked.

          //  CHECK_EQ(bottom[1]->shape()[1], neural_decision_forest_param.num_classes())
            //         <<"num_classes_ must be equal to bottom[1]->shape[1]!";

**Comment by luan-g** [comment]
You should add 'num_classes=5' to 'neural_decision_forest_param' in the script run.py

**Comment by iqbalnaved** [comment]
It worked! Thanks. Added label.shape[1] to the num_classes. Also, I had a unicode string issue with dirname(__FILE__) , typecasting to str solved that issue.
