### ISSUE TITLE
bash data/ldl/get_ldl.sh

### ISSUE THREAD

**Issue by ayantian** [zeakey/LDLForest#3]
Hi,
Thank you very much for sharing your code. One thing that puzzles me is that the code dose not provide "data/ldl/get_ldl.sh" . The link “http://kaiz.xyz/ldlf” you provided also seems to have expired. Can you upload the data again?
I am very looking forward to your help.
Best wishes!
Chen

**Comment by luan-g** [comment]
You can download the dataset from “http://7xocv2.dl1.z0.glb.clouddn.com/dataset/LDL-datasets.zip”.
